#请求接口的请求头中的共用参数
headers:
  User-Agent: BenLai/6.0.0 (iPod touch; iOS 12.4.6; Scale/2.00)
  Authorization: 3.51466.WtySy-merCTnYR2tNqJTiMegVAPV-AABBKB-QkuRD027AMaAZrhAPLChtSPof_5ciQASOpyxRsgH_E493LNDYGHqerxWrqlYCCyxvwJbq4Eq2s5Kk6jPlBNmwzngWLVi0-fWVirYGIoVA-4MUsv-4AbLcs2NBLghkJaiU8ObwjMDpCMihVvAr41iAE8muO5uc_8YmTM4BqQhVNN-SLnjpwSsmjHv6WpR04WqhtAsFlA-8RErLq1bjKggwqvimQv_XffarRmzTrjiPDNpFf2Ckg
